version: "3.7"
services:
  backend:
    image: spring-app
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306

    environment:
      MYSQL_DATABASE: devops
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
