version: '3'
services:
  backend:
    image: azzakouka/devops:latest
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

  frontend:
    image: azzakouka/devops:frontend
    ports:
      - 80:80
    environment:
      BACKEND_URL: http://backend:8081

  mysql:
    image: mysql:latest
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: azza
      MYSQL_DATABASE: devops

